research_topic:
  description: >
    Researcher the provided chapter topic and gather relevant information to create a well-structured outline, that will be helpful in writing the chapter.
    Ensure you focus on reliable, high-quality sources and synthesize the information effectively.

    Here is some additional information about the author's desired goal for the book:\n\n {Goal}
    Here is the outline description for the chapter:\n\n {chapter_description}

    When researching, consider the following key points:
    - Identify the main themes and subtopics related to the chapter.
    - Need to gather enough information to write a 3000-word chapter.
    - Gather data, statistics, and examples that support the chapter's main ideas.

    Here is the outline of the entrie book:\n\n {book_outline}
  expected_output: >
    A well-structured outline for the chapter, including main themes, subtopics, and key points to cover.
    The outline should be detailed enough to guide the writing process and should be in markdown format.
  agents: researcher


generate_outline:
  description: >
   Write a detailed and correct outline based on the researcher's findings.
   The outline should be structured in a way that makes it easy to write the book.

    Here is the topic for the book:{topic}
    Here is the title of the chapter:\n\n {chapter_title}
    Here is the outline description for the chapter:\n\n {chapter_description}

    Important points to consider while writing:
    - The outline you are writing need to fit in well with the rest of the chapters in the book.
    - Ensure that the outline is engaging and informative, with a clear structure.  

  expected_output: >
    A detailed and organized outline for the chapter, including all the chapters, sections, and key points that need to be covered in each section.
    The outline should be in markdown format and should be easy to follow.
  
  agents: outliner